services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - URL=${DOMAIN_URL}
      - SUBDOMAINS${SWAG_SUBDOMAINS}
      - VALIDATION=${SWAG_VALIDATION_TYPE}
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
      - ONLY_SUBDOMAINS=false
    volumes:
      - ${SWAG_CONFIG_FOLDER:-./config}:/config
    ports:
      - ${HTTPS_PORT:-443}:443
      - ${HTTP_PORT:-80}:80
    restart: unless-stopped
    networks:
      - net

include:
  - path: ${NETWORK_CONFIG_FILE}